routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

app/Models/Project.php
<?php

namespace App\Models;

use App\Traits\BelongsToStore;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class Project extends Model
{
    use BelongsToStore;

    protected $guarded = [];
    protected $casts = [
        'shares' => 'array',
    ];
    public static $DONATE_ID = 99999;

    public static function booted()
    {
        static::creating(function (self $project) {
            if ($project->goal) {
                $project->remaining = $project->goal;
            }
        });
    }

    public function category()
    {
        return $this->belongsTo(ProjectCategory::class, 'project_category_id');
    }

    public function getLogoUrlAttribute()
    {
        return Storage::disk('image')->url($this->logo);
    }

    public function getShortDescriptionAttribute()
    {
        return Str::of($this->description)->stripTags()->limit(50)->value();
    }

    public function isDone()
    {
        return $this->is_done;
    }

    public function getCompletePercentAttribute()
    {
        $completionPercentage = (($this->goal - $this->remaining) / $this->goal) * 100;
        return number_format($completionPercentage);

        // return ($this->this->goal - $this->remaining) / 100;
    }

    public function forDonate()
    {
        return $this->donateable;
    }

    public function totalPayment()
    {
        return OrderItem::query()
            ->where('project_id', $this->id)
            ->sum('subtotal');
    }
}

app/Models/Slider.php
<?php

namespace App\Models;

use App\Traits\BelongsToStore;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Slider extends Model
{
    // use BelongsToStore;

    protected $guarded = [];

    public function getImageUrlAttribute()
    {
        return Storage::disk('image')->url($this->image);
    }
}

resources/views/web/account.blade.php
@extends('web.layouts.app')
@section('content')

    <!-- new design Account-->
    <section class="header ">
        <nav aria-label="breadcrumb" class="breadcrumb-bg">
            <div class="container">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="#">الرئيسية</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">الملف الشخصي</li>
                </ol>
            </div>
        </nav>
    </section>

    <div class="main-page">
        <section class="profile-main">
            <div class="container">
                <div class="row justify-center">
                    <div class="col-md-10 col-lg-8">
                        @if(session('success'))
                            <div class="alert alert-success"
                                 role="alert">
                                {{session('success')}}
                            </div>
                        @endif
                        <div class="proflie-inr">
                            <div class="profile-title text-center mb-3">
                                <h2>الملف الشخصي</h2>
                            </div>
                            <div class="profile-info">
                                <nav class="container">
                                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                                        <a class="nav-link active" id="nav-public-tab" data-toggle="tab"
                                           href="#nav-public" role="tab" aria-controls="nav-public"
                                           aria-selected="true">الكل
                                        </a>
                                        <a class="nav-link" id="nav-donation-tab" data-toggle="tab" href="#nav-donation"
                                           role="tab" aria-controls="nav-donation" aria-selected="false">
                                            التبرعات
                                        </a>
                                    </div>
                                </nav>
                                <div class="tab-content" id="nav-tabContent">
                                    <div class="tab-pane fade show active" id="nav-public" role="tabpanel"
                                         aria-labelledby="nav-public-tab">
                                        <div class="profile-info-img">
                                            <img src="{{asset('/assets/img/user.svg')}}">
                                            <h2>{{$user->name}}</h2>
                                        </div>
                                        <div class="profile-details text-right">
                                            <form action="{{ route('update-profile')}}" method="POST" id="profile">
                                                @csrf
                                                <input type="hidden" id="user_id" value="{{$user->id}}"
                                                       name="user_id">
                                                <div class="row">
                                                    <div class="col-12">
                                                        <div class="form-group profile-info-fo">
                                                            <label class="gr-top-label fo-input-head">الاسم</label>
                                                            <input type="text" class="form-control fo-input"
                                                                   name="name"
                                                                   placeholder="" value="{{$user->name}}">
                                                            @error('name')
                                                            <label for="" class="text-red-400">{{$message}}</label>
                                                            @enderror
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group profile-info-fo">
                                                            <label class="gr-top-label fo-input-head">البريد </label>
                                                            <input type="text" class="form-control fo-input"
                                                                   name="email" value="{{$user->email}}"
                                                                   placeholder="example@gmail.com">
                                                            @error('email')
                                                            <label for="" class="text-red-400">{{$message}}</label>
                                                            @enderror
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group profile-info-fo">
                                                            <label class="gr-top-label fo-input-head">رقم </label>
                                                            <input type="text" class="form-control fo-input"
                                                                   name="phone" placeholder="0501410202"
                                                                   value="{{$user->phone}}">
                                                            @error('phone')
                                                            <label for="" class="text-red-400">{{$message}}</label>
                                                            @enderror
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="profile-info-bt">
                                                    <button type="submit" name="submit" form="profile" class="btn">حفظ
                                                    </button>
                                                </div>
                                            </form>

                                        </div>
                                    </div>
                                    <div class="tab-pane fade show " id="nav-donation" role="tabpanel"
                                         aria-labelledby="nav-donation-tab">
                                        <div class="profile-info-img">
                                            <h2>سجل </h2>
                                        </div>
                                        <div class="reg-details text-start">
                                            @foreach($orders as $order )
                                                <div class="reg-details-inr">
                                                    <div class="reg-pro-info">
                                                        <h2>المشروع</h2>
                                                        <span>{{ $order->orderName() }}</span>
                                                    </div>
                                                    <div class="reg-pro-num text-center">
                                                        <h2>العدد</h2>
                                                        <span>{{ $order->orderCount() }}</span>
                                                    </div>
                                                    <div class="reg-price-info text-center">
                                                        <h2>المبلغ</h2>
                                                        <span>{{ $order->amount }} ر.س</span>
                                                    </div>
                                                </div>
                                            @endforeach
                                        </div>


                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <!-- new design Account-->

    <section class="header account-header flex justify-center align-center text-center">
        <div class="container">
            <h5>
                إدارة حسابي
            </h5>
        </div>
    </section>

    <script>
        // $.noConflict();
        $(document).ready(function () {
            $("#tab-donation2").click(function () {
                $(".donationselect").addClass("cd-tabs__item--selected");
                $(".donationselectpanel").addClass("cd-tabs__panel--selected");

                $(".accountselect").removeClass("cd-tabs__item--selected");
                $(".accountselectpanel").removeClass("cd-tabs__panel--selected");
            });
        });

    </script>

@endsection

resources/views/web/cart.blade.php
@extends('web.layouts.app')
@section('content')

    <section class="header cart-header flex justify-center align-center text-center">
        <div class="container">
            <h5>
                سلة التبرعات
            </h5>
        </div>
    </section>

    <!-- cart  -->
    <section class="header ">
        <nav aria-label="breadcrumb" class="breadcrumb-bg">
            <div class="container">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="#">الرئيسية</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">السلة</li>
                </ol>
                @if(session('response'))
                    <div class="alert text-center @if(session('response')['status']==true) alert-success @else alert-danger @endif"
                         role="alert">
                        {{session('response')['message']}}
                    </div>
                @endif
            </div>
        </nav>
        <div class="container">

        </div>
    </section>


    <div class="main-page">
        <section class="cart-main">
            <div class="container">
                <div class="row justify-center">
                    <div class="col-md-10">
                        <div class="cart-inr">
                            <div class="cart-title text-center">
                                <h2>السلة</h2>
                            </div>
                            <div class="row">
                                <div class="cart-inr-right">
                                    @forelse ($cart as $item)
                                        <div class="alert alert-warning alert-dismissible fade show"
                                             role="alert">
                                            <div class="cart-right-inr">
                                                <div class="row">
                                                    @if($item->project)
                                                        <div class="col-md-5">
                                                            <div class="cart-right-img">
                                                                <img src="{{ $item->project->logo_url }}" width="100"
                                                                     height="100"
                                                                     class="img-responsive rounded-circle"/>
                                                                <div class="cart-img-info">
                                                                    <h3>المشروع</h3>
                                                                    <p>{{ $item->project->title }}</p>
                                                                    @if ($item->options->name)
                                                                        <p>هدية ل
                                                                           : {{ $item->options->name }}</p>
                                                                        <p>{{ $item->options->mobile }}</p>
                                                                    @endif
                                                                </div>
                                                            </div>
                                                        </div>
                                                    @else
                                                        <div class="col-md-5">
                                                            <div class="cart-right-img">
                                                                <img src="" width="100"
                                                                     height="100"
                                                                     class="img-responsive rounded-circle"/>
                                                                <div class="cart-img-info">
                                                                    <h3>تبرع سريع</h3>

                                                                </div>
                                                            </div>
                                                        </div>
                                                    @endif
                                                    <div class="col-md-3 col-6">
                                                        <div class="cart-counter">
                                                            <div class="cart-counter-title">
                                                                <h2>العدد</h2>
                                                            </div>
                                                            <div class="cart-counter-inr">
                                                                <div class="number-input text-center">
                                                                    {{ $item->qty }}
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-3 col-6">
                                                        <div class="cart-price text-center">
                                                            <h2>السعر</h2>
                                                            <span data-th="Subtotal">{{ $item->price }}</span>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-1 d-flex align-items-center">
                                                        <button type="button" class="remove-from-cart close cls-bt"
                                                                onclick=""
                                                                data-row-id="{{ $item->rowId }}">
                                                            <i class="fas fa-times"></i>
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    @empty
                                        <div class="flex justify-content-center">
                                            لا يوجد شيء لعرضه
                                        </div>
                                    @endforelse
                                </div>
                            </div>
                            <div class="row">
                                <div class="basket-bag col-md-8">
                                    <img src="{{ asset('/assets/img/basket-bag.png') }}">
                                </div>
                                @if(\Cart::count())
                                    <div class="col-md-4">
                                        <div class="block">
                                            المجموع: {{\Cart::total()}}
                                        </div>
                                        <div class="text-left ml-5">
                                            <a onclick="requestPay()" class="btn btn-sm btn-primary">
                                                دفع
                                            </a>
                                        </div>
                                    </div>
                                @endif
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection
@section('scripts')
    <script>
        $('.remove-from-cart').on('click', function () {
            $(this).attr('disabled', 'disabled');
            let rawId = $(this).data('row-id');

            $.ajax({
                url: '{{route('remove-from-cart')}}',
                data: {
                    _token: '{{ csrf_token() }}',
                    rawId: rawId,
                },
                type: 'post',
                dataType: "json",
                success: function (response) {
                    location.reload();
                },
                error: function (message) {
                    Swal.fire({
                        icon: 'error',
                        title: 'حدث خطأ',
                        text: message.responseJSON.message,
                        confirmButtonText: 'تم',
                    })
                }
            });
            $(this).removeAttr('disabled');
        });

    </script>
@endsection

resources/views/web/home.blade.php
@extends('web.layouts.app')
@section('content')

    <style>
        .thiredcolor {
            background-color: var(--primary);
            color: #fff;
        }

        .secondarybtn {
            background-color: var(--secondary);

            color: #fff;
            border-radius: 30px;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .secondarybtn:hover {
            color: #fff;
            opacity: 0.9;
        }


        .thiredcolor:hover {
            color: #fff;
            opacity: 0.9;
        }

        .card-desgn .title-on-img {
            background-color: var(--primary);
            color: var(--background);
        }

        .projects button.btn.active {
            background-color: var(--primary);
            color: var(--background);
        }

        .msgerrorcon {
            margin-top: 10px;
            display: inline-block;
            width: 100%;
            background-color: #ffe9e9;
            border-right: 3px solid;
            color: #d80f0f;
            padding: 6px 10px;
            line-height: normal;
        }

        .svg-icon-cls svg {
            height: 25px;
            width: auto;
        }

        .svg-icon-cls svg path {
            fill: #fff;
        }

        .addincrem {
            margin: 5px 0 15px;
        }

        .tagboxsele {
            margin-bottom: 0;
        }

        .donate-button {
            position: absolute;
            bottom: 10%;
            right: 5%;
        }
    </style>

    <div class="main-page home-page">
        <section class="home-slide position-relative">
            <div class="container">
                <div class="swiper">
                    <div class="swiper-wrapper">
                        @foreach($sliders as $slider)
                            <div class="swiper-slide">
                                <strong class="title text-uppercase">{{$slider?->title}}</strong>
                                @if($slider->link)
                                    <a href="{{$slider->link}}" target="_blank" class="btn d-bt donate-button">تبرع</a>
                                @endif
                                <img class="img-fluid"
                                     style="background-image: url('{{asset($slider->image_url)}}')"/>
                            </div>
                        @endforeach
                    </div>
                    <div class="swiper-button-next">
                        <i class="fas fa-angle-right csb"></i>
                    </div>
                    <div class="swiper-button-prev">
                        <i class="fas fa-angle-left csb"></i>
                    </div>
                </div>
            </div>
        </section>
        {{--        @include('web.common.paysidebar')--}}
        @include('web.projects.list')
    </div>
    @include('web.modals.share')
    <script>
        function showShareURL(url) {
            $('#shareModal').modal('show');

            $('#shareModal #ghiras_link_text').val(url);
            $('#shareModal #whatsappShareLink').attr('href', 'https://wa.me/?text=' + url);
            $('#shareModal #twitterShareLink').attr('href', 'https://twitter.com/intent/tweet?url=' + url);
            $('#shareModal #facebookShareLink').attr('href', 'https://www.facebook.com/sharer/sharer.php?u=' + url);
        }

        function copyToClipboard() {
            try {
                var copyText = document.getElementById("ghiras_link_text");
                copyText.select();
                copyText.setSelectionRange(0, 99999); /*For mobile devices*/
                document.execCommand("copy");
            } catch (error) {
            }
        }
    </script>
@endsection